
const realtimeBusinessScreeningResponse = {
    "counts": {
        "exact": 0,
        "veryHigh": 0,
        "high": 0,
        "medium": 0,
        "low": 0,
        "veryLow": 220,
        "all": 220
    },
    "results": [
        {
            "id": "ff794f82-4192-4a23-a960-e6e8babf0b3c",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.145Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Drug Trafficking",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Street Killas",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Street Killas\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Street Killas\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"7837014(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Arbor Streets\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Cherry,Hartford,Orange\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"United States\"}}",
            "bridger_updated": "2017-03-16T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "ff4fdcce-f3f4-45eb-8e86-29b8e216d483",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.146Z",
            "database": "WorldCompliance",
            "category": "Enforcement",
            "subcategory": "Unauthorized",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "orange.compte-immobilier.com",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"orange.compte-immobilier.com\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"orange.compte-immobilier.com\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"12050230(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"France\"}}",
            "bridger_updated": "2022-03-01T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fd5ad560-79dc-4ad5-9c4c-7b497ec04a01",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.145Z",
            "database": "WorldCompliance",
            "category": "SOE",
            "subcategory": "Govt Linked Corp",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Home UK Limited",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Home UK Limited\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Home UK Limited\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"03014367(Other) | 11218487(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mosquito Way\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"HATFIELD\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Germany,United Kingdom\"}}",
            "bridger_updated": "2021-07-31T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fcd6d051-02b7-4781-821b-80a1a66487eb",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.146Z",
            "database": "WorldCompliance",
            "category": "SOE",
            "subcategory": "Govt Linked Corp",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Business Services India Technology Private Limited",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Business Services India Technology Private Limited\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Business Services India Technology Private Limited\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"8889091(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Abhinav El- 107\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Navi Mumbai\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"France,India\"}}",
            "bridger_updated": "2018-04-05T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fcbe2b02-529c-4b7f-bd95-bb1e06989c23",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.146Z",
            "database": "WorldCompliance",
            "category": "SOE",
            "subcategory": "Govt Linked Corp",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Personal Communications Services Limited",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Personal Communications Services Limited\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Personal Communications Services Limited\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"02178917(Other) | 11217002(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mosquito Way\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"HATFIELD\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Germany,United Kingdom\"}}",
            "bridger_updated": "2021-07-31T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fcb673ce-5ce5-4207-8e15-263b573fad77",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.146Z",
            "database": "WorldCompliance",
            "category": "SOE",
            "subcategory": "Govt Linked Corp",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Business Services Poland Sp.zo.o",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Business Services Poland Sp.zo.o\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Business Services Poland Sp.zo.o\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"5260016437(Other) | 8460032(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Aleje Jerozolimskie 65/79\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Warsaw\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"France,Poland\"}}",
            "bridger_updated": "2019-05-26T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fc59d927-1e50-45a6-8eba-19c42643c72f",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.145Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Money Laundering",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Bangladesh Limited",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Bangladesh Limited\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Bangladesh Limited\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"11807456(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Bangladesh\"}}",
            "bridger_updated": "2021-10-05T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fbb93828-0cbd-450a-b966-737b6361c4ab",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.145Z",
            "database": "WorldCompliance",
            "category": "SOE",
            "subcategory": "Govt Linked Corp",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange Innovation UK Ltd",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Innovation UK Ltd\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange Innovation UK Ltd\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"8278886(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"48, Warwick Street\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"London\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"France,United Kingdom\"}}",
            "bridger_updated": "2019-09-20T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "fa873596-5d2c-4cd4-884b-0cb5ea0e10e4",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.145Z",
            "database": "WorldCompliance",
            "category": "Enforcement",
            "subcategory": "Unauthorized",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "groupe-orange-bank.com",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"groupe-orange-bank.com\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"groupe-orange-bank.com\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"11590620(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"France\"}}",
            "bridger_updated": "2021-06-06T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "f6d53a43-6c10-43cd-be29-c0a87ca5a731",
            "job_id": "8562bf9e-974e-4fc6-a1b8-c71b030423d7",
            "job_entity_id": "fdb67933-b61e-492d-a118-8b27daf7fdfe",
            "updated_at": "2022-05-27T06:45:27.146Z",
            "database": "WorldCompliance",
            "category": "Enforcement",
            "subcategory": "Disciplined",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Orange and Rockland Utilities, Inc.",
            "entity_type": "Business",
            "mapped_entity_details": "{\"registeredName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange and Rockland Utilities, Inc.\"},\"tradingName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"orange\",\"matchedEntity\":\"Orange and Rockland Utilities, Inc.\"},\"ein\":{\"matchCriteria\":\"\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"0000074778(Other) | 11671512(ProprietaryUID)\"},\"addressLine1\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1 Blue Hill Plaza,4 Irving Place,390 W Rte 59\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"New York,Spring Valley\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"United States\"}}",
            "bridger_updated": "2021-07-19T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        }
    ],
    "paging": {
        "nextPage": "001700040000003210f6d53a436c1043cdbe29c0a87ca5a731f07ffffff5f07ffffff5",
        "totalPages": 22,
        "totalRecordsAvailable": 220
    },
    "filtersData": {
        "databases": [
            "WorldCompliance"
        ],
        "categories": [
            "Adverse Media",
            "Enforcement",
            "PEP",
            "SOE",
            "Sanction List"
        ],
        "subcategories": [
            "Administrative",
            "Antitrust Violations",
            "Conspiracy",
            "Debarred",
            "Disciplined",
            "Disqualified",
            "Drug Trafficking",
            "Excluded Party",
            "Financial Crimes",
            "Fraud",
            "Govt Linked Corp",
            "Govt Owned Corp",
            "Healthcare Fraud",
            "Labor Violations",
            "Money Laundering",
            "PEP Controlled Bus",
            "Tax Evasion",
            "Unauthorized"
        ]
    },
    "jobEntityId": "fdb67933-b61e-492d-a118-8b27daf7fdfe"
}
export default realtimeBusinessScreeningResponse;
