
const realtimeIndividualScreeningResponse = {
    "counts": {
        "exact": 0,
        "veryHigh": 0,
        "high": 0,
        "medium": 0,
        "low": 6,
        "veryLow": 8,
        "all": 14
    },
    "results": [
        {
            "id": "1eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "2eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "3eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "4eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "5eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "6eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "7eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "rrrrrrrr-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "8eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "9eb3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "10b3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "11b3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "12b3ea39-b817-4171-9fde-788e08e7685b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1972,1971\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2020-05-04T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "023d2e8e-c913-47a8-9d33-e1ac4bd5399a",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Adverse Media",
            "subcategory": "Extort-Rack-Threats",
            "match": "Low",
            "match_description": "Date of birth within 2 years and same country but not clear city connection or country mismatch",
            "name": "Mario Bros",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bros\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Partial\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"1983,1982\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Mexico\"}}",
            "bridger_updated": "2018-08-13T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "6dae6d44-fdd5-4d14-9654-64b30872245b",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Enforcement",
            "subcategory": "Conspiracy",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Mario Bross",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bross\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Kilometro 2.7 vía Bocas del Palo\"},\"city\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Jamundí\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Colombia\"}}",
            "bridger_updated": "2021-06-03T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        },
        {
            "id": "09d40d7e-73a2-4d14-85fe-e2bdd6bf2b4d",
            "job_id": "c96d4eb7-eca4-4a2f-a4b4-1a982bfc4e3d",
            "job_entity_id": "552c4718-2aa5-4741-a366-5999af87dafe",
            "updated_at": "2022-05-27T07:25:11.959Z",
            "database": "WorldCompliance",
            "category": "Enforcement",
            "subcategory": "Conspiracy",
            "match": "Very Low",
            "match_description": "Weak name match OR country mismatch OR Gender mismatch",
            "name": "Mario Bross",
            "entity_type": "Individual",
            "mapped_entity_details": "{\"firstName\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Jack\",\"matchedEntity\":\"Bross\"},\"middleName\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Mario\",\"matchedEntity\":\"\"},\"lastName\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"Bros\",\"matchedEntity\":\"Mario\"},\"dateOfBirth\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"addressLine1\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"city\":{\"matchCriteria\":\"Not Available\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"\"},\"country\":{\"matchCriteria\":\"Different\",\"matchCriteriaNumeric\":0,\"internalInfo\":\"\",\"matchedEntity\":\"Colombia\"}}",
            "bridger_updated": "2016-08-29T00:00:00.000Z",
            "comments": JSON.stringify(["DateListed: 2015-02-05","Occupation: Brother-in-law of Ryan Keith Zinke, Former Secretary of the United States Department of the Interior.","Source: International,Website","Level: National","Category: PEP | Subcategory: Family Member","Last updated: 2020-09-02","Sources: https://members.worldcompliance.com/metawatch2.aspx?id=d0194d12-7fe8-4310-882f-80854c7b343e","Sources: http://missoulian.com/news/local/obituaries/thursday-september-frances-anderson-stanley-ray-dale-zinke-eileen-rita/article_02acb369-c36f-5b3c-a2fb-1da06af980df.html"])
        }
    ],
    "paging": {
        "nextPage": null,
        "totalPages": 2,
        "totalRecordsAvailable": 14
    },
    "filtersData": {
        "databases": [
            "WorldCompliance"
        ],
        "categories": [
            "Adverse Media",
            "Enforcement"
        ],
        "subcategories": [
            "Conspiracy",
            "Extort-Rack-Threats"
        ]
    },
    "jobEntityId": "552c4718-2aa5-4741-a366-5999af87dafe"
}
export default realtimeIndividualScreeningResponse;
