version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    container_name: server-container
    environment:
      - CASSANDRA_HOST=host.docker.internal
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    expose:
      - '3001'
    ports:
      - '3001:3001'
#  client:
#    build:
#      context: .
#      dockerfile: ./packages/client/Dockerfile
#    container_name: client-container
#    expose:
#      - '3000'
#    ports:
#      - '3000:80'
